### ISSUE TITLE
Ultimas entradas. Card altura diferente.

### ISSUE THREAD

**Issue by farreusa** [python-chile/pythonchile.cl#15]
Mantener la misma altura.
![image](https://user-images.githubusercontent.com/36941609/114277394-ff5a9e00-99f8-11eb-8e5d-32059ba7338c.png)

**Comment by cmaureir** [comment]
Gracias! lo apliqué en la sección de coordinadores y se me olvidó hacerlo con los posts :)

**Comment by farreusa** [comment]
También debería de mantenerse en la parte inferior la fecha, el nombre y el botón, se vería mas estandarizado. Que el titulo sea el que solo varii de acuerdo al mas largo, aunque seria bueno colocar un máximo numero de caracteres.

**Comment by cmaureir** [comment]
@farreusa  Quizás podrías abrir otro issue con tus ideas, porque este ya lo cerré xD
