### ISSUE TITLE
Los enlaces al pie de página no apuntan donde corresponden

### ISSUE THREAD

**Issue by aweinstein** [python-chile/pythonchile.cl#18]
Los enlaces al pie de página no apuntan a donde corresponde.

![Screenshot from 2021-04-10 15-30-19](https://user-images.githubusercontent.com/123405/114282406-ce3a9780-9a11-11eb-8b0c-72011c3c6822.png)

**Comment by cmaureir** [comment]
Arreglado en https://github.com/python-chile/pythonchile.cl/pull/21
