### ISSUE TITLE
Los enlaces en el encabezado de la página no coinciden con los del pie de página.

### ISSUE THREAD

**Issue by aweinstein** [python-chile/pythonchile.cl#19]
Esto no sé si es un bug o una decisión de diseño :)  Los link en el encabezado de la página no coinciden con los del pie de página. En el encabezado no está ni `Grupos` ni `Eventos`.

![Screenshot from 2021-04-10 15-34-21](https://user-images.githubusercontent.com/123405/114282495-4739ef00-9a12-11eb-94c8-309dcc849c61.png)
![Screenshot from 2021-04-10 15-30-19](https://user-images.githubusercontent.com/123405/114282496-4739ef00-9a12-11eb-923a-19720ed69049.png)

**Comment by cmaureir** [comment]
Toda la razón, creo que debería ser igual, pero como Comunidad solo abre un menu con 2 elementos, creo que voy a dejar esos dos elementos en vez de Comunidad.
