### ISSUE TITLE
Incluir logos de patrocinantes 

### ISSUE THREAD

**Issue by elkabuitrago** [python-chile/pythonchile.cl#59]
@cmaureir una opción con solo el logo de IT-Talent 

![image](https://user-images.githubusercontent.com/45636874/152614096-8e857184-3dc5-4f51-adaa-b513dd34958e.png)

Todos los logos de los Platinum (serían los logos con el fondo apropiado es para ver la distribución)

![image](https://user-images.githubusercontent.com/45636874/152621226-ed297eee-950a-42d7-ba72-ec493605a744.png)

**Comment by elkabuitrago** [comment]
logos transparentes 

![image](https://user-images.githubusercontent.com/45636874/152651114-37528b0c-fd63-4f09-919b-cbde934d3dc8.png)

**Comment by cmaureir** [comment]
me gusta el último screenshot, pero igual incluiría el texto que habías puesto en la primera versión, ya sea en el costado como abajo del título. Muchas gracias @elkabuitrago 

Sería bueno hacer un merge  solo de las empresas que ya hemos conversado y no todos al mismo tiempo.
Si ya está lo de IT-talent, quizás agregarlo.

**Comment by elkabuitrago** [comment]
> me gusta el último screenshot, pero igual incluiría el texto que habías puesto en la primera versión, ya sea en el costado como abajo del título. Muchas gracias @elkabuitrago
> 
> Sería bueno hacer un merge solo de las empresas que ya hemos conversado y no todos al mismo tiempo. Si ya está lo de IT-talent, quizás agregarlo.

Si, en principio solo el de IT- Talent, el último seria una vez que concretemos con las otras empresas

**Comment by elkabuitrago** [comment]
que te parece así?

![image](https://user-images.githubusercontent.com/45636874/152687425-61eee46a-8cf9-4a13-ae73-82d19b21eddf.png)
