### ISSUE TITLE
Enlaces erróneos en redes sociales de coordinadores

### ISSUE THREAD

**Issue by sebastiandres** [python-chile/pythonchile.cl#70]
Pillé 3 enlaces incorrectos (no se abren correctamente) en la página de coordinadores (content/pages/coordinacion.md)
Cris Hernández https://twitter.com/crishernandezco
Franklin Arredondo https://www.linkedin.com/in/fearredondo/
Jhoselyn Pajuelo Villanueva https://www.linkedin.com/in/jhoselynpajuelovillanueva
No los corregí porque no tengo el enlace correcto.

**Comment by pablolirag** [comment]
No son miembros activos de la comunidad, creo que es mejor dejar tal cual  esos datos.
